name: CozeSharp Release and Packaging

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发此工作流

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # 根据项目实际使用的 .NET 版本进行修改

      - name: Build CozeSharp
        run: dotnet build CozeSharp/CozeSharp.csproj --configuration Release

      - name: Pack CozeSharp for NuGet
        run: dotnet pack CozeSharp/CozeSharp.csproj --configuration Release --output nupkgs

      - name: Publish CozeSharp to NuGet
        run: dotnet nuget push nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        continue-on-error: false

      - name: Build CozeSharp_ConsoleApp
        run: dotnet publish CozeSharp_ConsoleApp/CozeSharp_ConsoleApp.csproj -c Release -r win-x64 --self-contained true -o publish

      - name: Create Windows Application Package
        run: |
          cd publish
          Compress-Archive -Path . -DestinationPath CozeSharp_ConsoleApp.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            此版本包含以下更新：
            - 待添加具体更新内容

      - name: Upload Windows Application Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: publish/CozeSharp_ConsoleApp.zip
          asset_name: CozeSharp_ConsoleApp.zip
          asset_content_type: application/zip
