name: Automated Release

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发此工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # 根据项目实际使用的 .NET 版本进行修改

      - name: Build project
        run: dotnet build --configuration Release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            此版本包含以下更新：
            - 待添加具体更新内容

      - name: Package and Upload Release Asset
        run: |
          dotnet publish CozeSharp/CozeSharp.csproj -c Release -o publish
          zip -r CozeSharp.zip publish
          gh release upload ${{ github.ref_name }} CozeSharp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pack NuGet Package
        run: |
          # 从标签名中提取版本号
          TAG=${{ github.ref_name }}
          VERSION=${TAG:1}  # 移除v前缀
          
          # 创建NuGet包
          dotnet pack CozeSharp/CozeSharp.csproj -c Release -o nuget --version-suffix $VERSION

      - name: Push NuGet Package
        run: |
          dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
